name: Compile Typst
on:
  push:
    paths:
      - '**.typ'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4

      - name: Typst setup
        uses: typst-community/setup-typst@v3

      - name: Typst src to PDF compilation
        run: typst compile main.typ

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Latest Build"
          files: main.pdf
          make_latest: true
